version: '3.8'

networks:
  eats-network:
    driver: 'bridge'
volumes:
  mysql_data:
  servers:

services:
  mysql:
    container_name: 'eats_mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=eats'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'
    networks:
      - 'eats-network'
    volumes:
      - 'mysql_data:/var/lib/mysql'
  api:
    build:
      context: .
    container_name: 'order_api'
    environment:
      - 'MYSQL_HOST=eats_mysql'
      - 'NOTIFICATION_HOST=notification_server'
    ports:
      - '9000:9000'
    depends_on:
      - 'mysql'
    networks:
      - 'eats-network'
    volumes:
      - 'servers:/app'
  notification:
    container_name: 'notification_server'
    build: '../eats-notification'
    ports:
      - '5000:5000'
      - '7256:7256'
      - '5246:5246'
    networks:
      - 'eats-network'
  payments:
    container_name: 'payments_server'
    build: '../eats-payments'
    ports:
      - '1099:1099'
    networks:
      - 'eats-network'
    volumes:
      - 'servers:/app'