version: '3.8'

networks:
  eats-network:
    driver: 'bridge'
volumes:
  mysql_data:

services:
  mysql:
    container_name: 'eats_mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=eats'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'
    networks:
      - 'eats-network'
    volumes:
      - 'mysql_data:/var/lib/mysql'
  api:
    build:
      context: .
    container_name: 'order_api'
    environment:
      - 'MYSQL_HOST=eats_mysql'
    ports:
      - '9000:9000'
    depends_on:
      - 'mysql'
    networks:
      - 'eats-network'